### ISSUE TITLE
Añadir función de movimiento player2

### ISSUE THREAD

**Issue by fantalavapies** [fantalavapies/dev_vs_sys#5]
La función aumentarTurno() ahora mismo es esta:

function aumentarTurno()
	player1.nturno = player1.nturno + 1
	calcularFila()
	calcularCol()
end

Eso quiere decir que el turno del player2 nos la suda, pero que no cuesta aumentarle tambien el turno de paso así por ejemplo:

	player2.nturno = player2.nturno + 1

Eso nos lleva a que cada vez que aumentamos turno como jugador (player1) el player2 aumenta. Pero no tendría que ser dentro de esa función de aumentar turno y si dentro de otra a la que se llama desde esta.

Esa función es la de moverPlayer2() . No existente.

**¿Que hace esa función?**

Pues tendría  que ser la que posicionase en otra room al player2.

Player2 así como player1 cuando se selecciona personaje y comienza el juego van a una room de forma aleatoria. Una de las 16 posibles.

Cuando player1 gasta turno (ya sea cogiendo algo, mirando, moviendose a otra room) se aumenta el valor y es cuando player2 ha de moverse.

La función por tanto inicialmente antes del turno 60 será sencilla. Se moverá player2 a alguna de las opciones disponibles en la room que se encuentra. Eso quiere decir que si está en la 16 no podrá ir al sur ya que no existe salida por allí ni tampoco al este pero si al sur y al norte. En base a las posibilidades aleatoriamente elige entre ellas y una vez determina una salida  existiria un 50% de probabilidad de que se mueva o no. Eso quiere decir que no siempre necesariamente en cada turno del player1 el 2 se mueve. Puede quedarse quizas en la misma room.

Luego a partir del turno 60 si que comienza a ir a por el player1. Ya no actua de forma aleatoria. 
Sabe la posición del player1 (la room, la columna y la fila). 

| 01 | 02 | 03 | 04 | ---> fila 1
| 05 | 06 | 07 | 08 | ---> fila 2
| 09 | 10 | 11 | 12 | ---> fila 3
| 13 | 14 | 15 | 16 | ---> fila 4

Por tanto si están en la misma fila se irá a la posición más cercana a la columna del player1.
Si no está en la misma fila irá a la posición más cercana a la fila del player1.
Y así serán todos sus movimientos. Siempre intentando alcanzar al player1. Eso quiere decir que en pocos turnos si el player1 no se mueve player2 terminará llegando hasta él. 

Y eso se hace para forzar que alguna vez ambos jugadores se encuentren. De lo contrario el juego termina en el turno 170 sin que se vean y termina sin que sea posible terminarlo. Es necesario ese encuentro por tanto y de esa forma se fuerza.

**Comment by fantalavapies** [comment]
Se le ha de dar una pensada junto a una función que comprueba si ambos están ya en la misma room.
Y se ha de crear una función distinta para player2 cuando comienza el juego para evitar que caiga en la misma room que player1. Una función que lo posiciona sabiendo donde está player1 y evitando no caer en misma columna ni misma fila al menos.

**Comment by xaloc33** [comment]
A partir del turno 60 que hace el player2 si las salidas de la room no le permiten acercarse al player1? Tiene el player2 información sobre todas las salidas de las rooms, solo de las rooms que ha visitado o solo de la room en la que se encuentra?

**Comment by fantalavapies** [comment]
Tanto player1 como player2 siempre se pueden mover de una fila a otra. De modo que siempre podrán acercarse primero por fila y luego por columna.

| 01 | 02 | 03 | 04 | ---> fila 1
| 05 | 06 | 07 | 08 | ---> fila 2
| 09 | 10 | 11 | 12 | ---> fila 3
| 13 | 14 | 15 | 16 | ---> fila 4

La room 01 por ejemplo solo puedes ir al este y al sur. Es la esquina superior izquierda.
La room 04 por ejemplo solo puedes ir al oeste y al sur. Es la esquina superior derecha.
La room 13 por ejemplo solo puedes ir al este y al norte. Es la esquina superior izquierda.
La room 16 por ejemplo solo puedes ir al oeste y al norte. Es la esquina superior derecha.

El player2 a partir del turno 60 o el que sea siempre tiene opción para acercarse al player1 sea cualquiera que sea la room en la que esté. Digamos que las rooms interiores estan comunicadas con todas. Es como si existiesen rooms con 4 salidas en todo lo interior. 

Eso se aprecia en el disquete con las direcciones. Un disquete rosa de los vientos.
Cuando andas en la zona oeste del edificio no puedes ir más hacia el oeste, lo mismo para el sur, norte y este. Eso va indicando que estás en la zona más sur del edificio, la más norte, etc...

Añadir complejidad al interior de las rooms limitando salidas hace que ya sea un circuito en vez de un tablero de ajedrez.

**Comment by fantalavapies** [comment]
> Tiene el player2 información sobre todas las salidas de las rooms, solo de las rooms que ha visitado o solo de la room en la que se encuentra?

El player2 tiene información sobre donde está el player1, su room, su columna y su fila. Pero no usa esos valores hasta el turno 60. 
De esa forma primero se va moviendo aleatoriamente sin conocimiento y a partir del 60 (o el turno que finalmente se ponga viendo si es adecuado)  simplemente se va acercando.

**Comment by xaloc33** [comment]
Si soy yo que no he mirado bien las salidas de las rooms antes de preguntar y pensaba que podia ser un circuito y no como un tablero. Esto lo simplifica un poco y sabiendo donde esta no debería haber ningún problema para perseguir al player1.

**Comment by xaloc33** [comment]
He hecho la función moverPlayer2 de la siguiente forma:
```lua

  function moverPlayer2()
    if player1.nturno < 60 then

      if math.random() < 0.5 then
        salidas = {}

        if room.norte == 1 then salidas[#salidas+1] = "norte" end
        if room.este == 1 then salidas[#salidas+1] = "este" end
        if room.sur == 1 then salidas[#salidas+1] = "sur" end
        if room.oeste == 1 then salidas[#salidas+1] = "oeste" end

        salida = salidas[love.math.random(1,#salidas)]

        if salida == "norte" then player2.fila = player2.fila - 1 end
        if salida == "este" then player2.col = player2.col + 1 end
        if salida == "sur" then player2.fila = player2.fila + 1 end
        if salida == "oeste" then player2.col = player2.col - 1 end

        calcularRoom()

      end

    else
      perseguirPlayer1()
    end

  end

  function perseguirPlayer1()

    if player1.fila == player2.fila then

      if player1.col - player2.col < 0 then
        player2.col = player2.col - 1
      else
        player2.col = player2.col + 1
      end

    else

      if player1.fila - player2.fila < 0 then
        player2.fila = player2.fila - 1
      else
        player2.fila = player2.fila + 1
      end

    end

    calcularRoom()

  end

  function calcularRoom()

    --player1 (para perseguirPlayer1 y moverPlayer2 no se usa pero puede servir en otro momento)
    player1.room = (player1.fila - 1)*4 + player1.col

    --player2
    player2.room = (player2.fila - 1)*4 + player2.col

  end


```

Esto en principio funciona, el problema es que la room activa es la room de player1 por lo que el player2 no va tener las salidas adecuadas.
Para arreglarlo se puede poner todos los casos de todas las rooms a mano, o no se si se podria cargar la room del player2 sin que moleste en el resto del juego y dejarlo así. 

Para el movimiento del player2 a partir del turno 60, he hecho la función perseguirPlayer1() que se llama directamente des de moverPlayer2(), en caso de haber llegado al turno 60.
Creo que esta función si que hace lo que habías propuesto.

Espero que te sirva para algo.

**Comment by fantalavapies** [comment]
Justo me has pillado realizando la función:


function aumentarTurno()
	player1.nturno = player1.nturno + 1
	calcularFila()
	calcularCol()
	desplazarPlayer2()
end


function desplazarPlayer2()
	if player1.room ~= player2.room then
		calcularCol()
		calcularFila()
		print("P1 - Room: " .. player1.room .. " Fila: " .. player1.fila .. " Col: " .. player1.col)
		print("P2 - Room: " .. player2.room .. " Fila: " .. player2.fila .. " Col: " .. player2.col)
		comprobarSalidasPlayer2(player2.room)
		if salidasPosiblesPlayer2 ~= null then
			local opciones = {}
			for key, value in pairs(salidasPosiblesPlayer2) do
				table.insert(opciones, key)
			end
			player2.room = salidasPosiblesPlayer2[opciones[math.random(#opciones)]]
		end
	end
end

function comprobarSalidasPlayer2(rp2)
	if player2.room == 1 then salidasPosiblesPlayer2 = {1,2,5} end
	if player2.room == 2 then salidasPosiblesPlayer2 = {2,1,3,6} end
	if player2.room == 3 then salidasPosiblesPlayer2 = {3,2,4,7} end	
	if player2.room == 4 then salidasPosiblesPlayer2 = {4,3,8} end
	
	if player2.room == 5 then salidasPosiblesPlayer2 = {5,1,6,9} end
	if player2.room == 6 then salidasPosiblesPlayer2 = {6,2,7,10,5} end
	if player2.room == 7 then salidasPosiblesPlayer2 = {7,3,8,11,6} end	
	if player2.room == 8 then salidasPosiblesPlayer2 = {8,4,12,7} end
	
	if player2.room == 9 then salidasPosiblesPlayer2 = {9,5,10,13} end
	if player2.room == 10 then salidasPosiblesPlayer2 = {10,6,11,14,9} end
	if player2.room == 11 then salidasPosiblesPlayer2 = {11,7,12,15,10} end	
	if player2.room == 12 then salidasPosiblesPlayer2 = {12,8,16,11} end
	
	if player2.room == 13 then salidasPosiblesPlayer2 = {13,9,14} end
	if player2.room == 14 then salidasPosiblesPlayer2 = {14,10,15,13} end
	if player2.room == 15 then salidasPosiblesPlayer2 = {15,11,16,14} end	
	if player2.room == 16 then salidasPosiblesPlayer2 = {16,12,15} end
end

**Comment by fantalavapies** [comment]
Ahora mismo la función perseguir player me vale. Voy a ver si la añado.
Pero esto con esas funciones chuta ya. EL player 2 se va moviendo.

Creo que lleva a engaño unas variables que puse en la room de las salidas posibles. Que si mal no recuerdo era pensando en esto pero lo mismo ya no sirven para nada. Lo compruebo y veo como integrar la función de perserguir player.

**Comment by fantalavapies** [comment]
Dame un rato y miro como integrar tu función con la mía. Pillar lo que sea mejor.
Nos hemos solapado buscando una solución a esa función. Pero yo de momento no he incorporado la de perseguir player. Voy a mirar como integrarlo.

**Comment by xaloc33** [comment]
Lo único que le faltaría a tu función de desplazarPlayer2 es la posibilidad de no moverse de la sala antes del turno 60 si es que quieres que tenga esa posibilidad.
Y no te preocupes usa lo que te vaya mejor que para eso es tu juego.

**Comment by fantalavapies** [comment]
if room.norte == 1 then love.graphics.printf("N", 720, 475, love.graphics.getWidth()) end
	if room.este == 1 then love.graphics.printf("E", 760, 515, love.graphics.getWidth()) end
	if room.sur == 1 then love.graphics.printf("S", 720, 560, love.graphics.getWidth()) end
	if room.oeste == 1 then love.graphics.printf("O", 680, 515, love.graphics.getWidth()) end

Eso solo afecta al player1 y su finalidad era la de usarse para dibujar el disquete. No le sirve al player 2 y por eso he optado por darselas en una función (mejorable todo sea dicho) en la que se comprueban las salidas.

Respecto a no moverse he incorporado entre las opciones aleatorias la posibilidad de la actual room.
Y algunas veces no se mueve, pero eso no se puede saber.

Pero le falta que incorpore de tus funciones la comprobación del turno 60. Voy con ello :).
Gracias.

**Comment by xaloc33** [comment]
lo primero es que más o menos funcione como uno quiere, revisar y afinar se puede hacer más adelante.
la función la he hecho como me ha parecido más fácil de hacer si crees que hay un método mejor ningún problema

**Comment by fantalavapies** [comment]
Está bien. Es mucho mejor que lo que hubiera realizado yo.
Ya está incorporado. He dejado unos prints para que se vea y he bajado de momento a 20 cuando empezará a perseguir. 

Cierro esto y ya serían detalles de mejorar eso.

De momento he realizado commit con los prints para que se pueda probar.
